# Generated by Django 3.1.4 on 2021-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Cin', models.CharField(max_length=100)),
                ('Rf', models.CharField(max_length=100)),
                ('Prestation', models.CharField(blank=True, choices=[('M.E.C', 'M.E.T'), ('MT', 'MT'), ('lotissement', 'Lotissement'), ('MT Fustion', 'MT Fustion'), ('Fusion total', 'Fusion total'), ('copropriété', 'Copropriété'), (' Plan de bornage', ' Plan de bornage'), ('Plan cote', 'Plan cote'), ('Partage', 'Partage'), ('Expertise foncier', 'Expertise foncier')], max_length=100)),
                ('Lieu', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('levé', 'levé'), ('traitement', 'traitement'), ('controle de cadastre', 'controle de cadastre'), ('recepese delivré', 'recepese delivré')], default='confirmed', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
